import * as vscode from 'vscode';
import { Session } from '../types/session';
import { GitOperations } from './gitOperations';

export class PRWorkflow {
  constructor(private gitOps: GitOperations) {}

  /**
   * Generate GitHub PR creation URL
   */
  async generatePRLink(
    session: Session,
    baseBranch: string = 'main'
  ): Promise<string | null> {
    try {
      const remoteUrl = await this.gitOps.getRemoteUrl('origin', session.workspace);
      const { owner, repo } = this.parseGitHubUrl(remoteUrl);

      if (!owner || !repo) {
        return null;
      }

      const headBranch = session.branch || 'unknown';
      const title = encodeURIComponent(session.task);
      const body = this.generatePRBody(session);

      return `https://github.com/${owner}/${repo}/compare/${baseBranch}...${headBranch}?expand=1&title=${title}&body=${encodeURIComponent(body)}&labels=ollama-copilot`;

    } catch (error) {
      console.error('Failed to generate PR link:', error);
      return null;
    }
  }

  /**
   * Parse GitHub URL to extract owner and repo
   */
  private parseGitHubUrl(url: string): { owner: string | null; repo: string | null } {
    // Handle HTTPS format
    const httpsMatch = url.match(/github\.com[:/]([^/]+)\/([^/.]+)(\.git)?$/);
    if (httpsMatch) {
      return { owner: httpsMatch[1], repo: httpsMatch[2] };
    }

    // Handle SSH format
    const sshMatch = url.match(/git@github\.com:([^/]+)\/([^/.]+)(\.git)?$/);
    if (sshMatch) {
      return { owner: sshMatch[1], repo: sshMatch[2] };
    }

    return { owner: null, repo: null };
  }

  /**
   * Generate PR body from session
   */
  private generatePRBody(session: Session): string {
    const lines = [
      '## Generated by Ollama Copilot 🤖',
      '',
      `**Task**: ${session.task}`,
      `**Model**: ${session.model}`,
      '',
      '### Changes',
      ''
    ];

    if (session.filesChanged.length > 0) {
      lines.push(`Modified ${session.filesChanged.length} file(s):`);
      for (const file of session.filesChanged.slice(0, 10)) {
        lines.push(`- ${file}`);
      }
      if (session.filesChanged.length > 10) {
        lines.push(`- ... and ${session.filesChanged.length - 10} more`);
      }
    } else {
      lines.push('No files tracked');
    }

    lines.push('');
    lines.push('### Tool Executions');
    lines.push('');
    lines.push(`Total operations: ${session.toolCalls.length}`);

    if (session.errors.length > 0) {
      lines.push('');
      lines.push('### ⚠️ Errors Encountered');
      lines.push('');
      for (const error of session.errors.slice(0, 3)) {
        lines.push(`- ${error}`);
      }
    }

    return lines.join('\n');
  }

  /**
   * Show PR creation prompt
   */
  async showCompletionPrompt(session: Session): Promise<void> {
    const prLink = await this.generatePRLink(session);

    const message = `✅ Agent completed task!\n\nBranch: ${session.branch}\nFiles changed: ${session.filesChanged.length}`;

    const actions: vscode.MessageItem[] = [];

    if (prLink) {
      actions.push({ title: '🔀 Create PR' });
    }
    
    actions.push(
      { title: '👀 View Changes' },
      { title: '📋 Copy Branch' }
    );

    const choice = await vscode.window.showInformationMessage(
      message,
      ...actions
    );

    switch (choice?.title) {
      case '🔀 Create PR':
        if (prLink) {
          await vscode.env.openExternal(vscode.Uri.parse(prLink));
        }
        break;

      case '👀 View Changes':
        await this.showGitDiff(session);
        break;

      case '📋 Copy Branch':
        if (session.branch) {
          await vscode.env.clipboard.writeText(session.branch);
          vscode.window.showInformationMessage(`Copied: ${session.branch}`);
        }
        break;
    }
  }

  /**
   * Show git diff for session changes
   */
  private async showGitDiff(session: Session): Promise<void> {
    if (!session.filesChanged.length) {
      vscode.window.showInformationMessage('No files changed');
      return;
    }

    // Open git diff view
    try {
      await vscode.commands.executeCommand('git.openChange', session.filesChanged[0]);
    } catch (error) {
      vscode.window.showWarningMessage('Could not open diff view');
    }
  }
}
